# Generated by Django 5.0.6 on 2024-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend_bistro', '0002_customer_driver_rename_customerorder_order_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Drink', 'Drink'), ('Breakfast', 'Breakfast'), ('Appetizer', 'Appetizer'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Drink', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cuisine',
            field=models.CharField(choices=[('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Southern', 'Southern'), ('American', 'American'), ('Asian', 'Asian'), ('Mediterranean', 'Mediaterranea'), ('International', 'International')], default='Italian', max_length=200),
        ),
    ]
