# Generated by Django 5.0.6 on 2024-05-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend_bistro', '0004_menuitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='license_number',
            new_name='license_plate_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_make',
            field=models.CharField(default='loading', max_length=30),
            preserve_default=False,
        ),
    ]
